### ISSUE TITLE
Missing horizontal lines

### ISSUE THREAD

**Issue by eko24ive** [bogdanlotuk/Task5#1]
![image](https://cloud.githubusercontent.com/assets/25591824/22922606/24858eae-f2a7-11e6-8541-8c1e3ad0f3c0.png)

**Use design reference:**
![image](https://cloud.githubusercontent.com/assets/25591824/22922621/307c0990-f2a7-11e6-8347-2016e59b63a8.png)

**Comment by bogdanlotuk** [comment]
Fixed

**Comment by eko24ive** [comment]
Good job !
