### ISSUE TITLE
Footer mismatch

### ISSUE THREAD

**Issue by eko24ive** [bogdanlotuk/Task5#2]
Here is your footer
![image](https://cloud.githubusercontent.com/assets/25591824/22922547/e43d5066-f2a6-11e6-9ca1-46b65519349d.png)

Please use design reference:
![image](https://cloud.githubusercontent.com/assets/25591824/22922554/edbf171e-f2a6-11e6-986d-ab1cf1722a5f.png)

**Comment by bogdanlotuk** [comment]
Fixed

**Comment by eko24ive** [comment]
Nice
