### ISSUE TITLE
Top section issues

### ISSUE THREAD

**Issue by eko24ive** [bogdanlotuk/Task5#3]
According to [design](http://i.imgur.com/0LIv36I.png) top section must be full width.
Please fix.

**Comment by eko24ive** [comment]
You fixed it in your previous commit, nice job !

**Comment by eko24ive** [comment]
Actually not, please extend only top section width:
![image](https://cloud.githubusercontent.com/assets/25591824/23058543/1e7ce63e-f4fe-11e6-8191-ab33198e55ad.png)

**Comment by bogdanlotuk** [comment]
Check please

**Comment by eko24ive** [comment]
Well done !
