### ISSUE TITLE
Font shadow

### ISSUE THREAD

**Issue by eko24ive** [bogdanlotuk/Task5#4]
Text shadow is missing, compare your page:
![image](https://cloud.githubusercontent.com/assets/25591824/22999845/41100406-f3e6-11e6-8c15-46ad6a02e517.png)

To design:
![image](https://cloud.githubusercontent.com/assets/25591824/22999848/48a7eb2a-f3e6-11e6-9520-2c73d8bd6bd7.png)

**Comment by bogdanlotuk** [comment]
Fixed

**Comment by eko24ive** [comment]
Well done !
