### ISSUE TITLE
Layout issue

### ISSUE THREAD

**Issue by eko24ive** [bogdanlotuk/Task5#5]
Some of your content seems to have alignment issue on high width devices:
![image](https://cloud.githubusercontent.com/assets/25591824/23116584/e710cc3a-f753-11e6-9cec-92d8d0943fd4.png)

According to design content had to be aligned between red lines which you can see on the screenshot.

**Comment by bogdanlotuk** [comment]
Check please

**Comment by eko24ive** [comment]
Awesome !
