### ISSUE TITLE
Unnecessary overflow

### ISSUE THREAD

**Issue by eko24ive** [bogdanlotuk/Task5#6]
I can see **horizontal scrollbar** at the bottom, which means some of your elements width is bigger that `body` width:
![image](https://cloud.githubusercontent.com/assets/25591824/23116750/e89b434a-f754-11e6-8995-b8dd2b53247d.png)

This could be cause becouse youre using absolute units values, e.g. `width: 1138px;`
Consider using relative-based variables such as: `%`, `vh`, `vw` etc.

**Comment by eko24ive** [comment]
This could help you work it through https://css-tricks.com/findingfixing-unintended-body-overflow/

**Comment by bogdanlotuk** [comment]
Check please

**Comment by eko24ive** [comment]
Well done !
